using CommunityToolkit.Mvvm.Messaging;
using M.A.G.U.S.Assistant.Models;
using M.A.G.U.S.Utils;
using Mtf.LanguageService.MAUI;
using Mtf.Maui.Controls.Messages;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Diagnostics;
using System.Reflection;
using System.Windows.Input;

namespace M.A.G.U.S.Assistant.ViewModels;

internal partial class ImagesViewModel : INotifyPropertyChanged
{
    public event PropertyChangedEventHandler? PropertyChanged;

    public ObservableCollection<ImageItem> AllImages { get; } = [];
    public ObservableCollection<ImageItem> FilteredImages { get; } = [];

    private string searchText = String.Empty;
    public string SearchText
    {
        get => searchText;
        set
        {
            if (searchText == value)
            {
                return;
            }

            searchText = value;
            OnPropertyChanged(nameof(SearchText));
            ApplyFilter();
        }
    }

    private ImageItem? selectedImage;
    public ImageItem? SelectedImage
    {
        get => selectedImage;
        set
        {
            if (selectedImage == value)
            {
                return;
            }

            selectedImage = value;
            OnPropertyChanged(nameof(SelectedImage));
            if (selectedImage != null)
            {
                _ = PreviewAsync(selectedImage);
            }
        }
    }

    public ICommand PreviewCommand { get; }

    public ImagesViewModel()
    {
        PreviewCommand = new Command<ImageItem>(item => _ = PreviewAsync(item));
        LoadImages();
        ApplyFilter();
    }

    private void LoadImages()
    {
        try
        {
            var asm = Assembly.GetExecutingAssembly();
            var resourceName = asm.GetManifestResourceNames().FirstOrDefault(n => n.EndsWith("images_manifest.txt", StringComparison.OrdinalIgnoreCase));
            if (resourceName == null)
            {
                WeakReferenceMessenger.Default.Send(new ShowErrorMessage("The images_manifest.txt not found in embedded resources. It should be generated by the GenerateImageManifest project target."));
                return;
            }

            using var stream = asm.GetManifestResourceStream(resourceName);
            if (stream == null)
            {
                return;
            }

            using var reader = new StreamReader(stream);
            var lines = reader.ReadToEnd().Split('\n', StringSplitOptions.RemoveEmptyEntries);

            foreach (var line in lines)
            {
                var trimmed = line.Trim();
                if (trimmed.Length == 0)
                {
                    continue;
                }

                var display = Path.GetFileNameWithoutExtension(trimmed).Split('.')[^1];
                var item = new ImageItem
                {
                    ResourceId = trimmed,
                    DisplayName = Lng.Elem(display.ToName())
                };

                AllImages.Add(item);
            }
        }
        catch (Exception ex)
        {
            WeakReferenceMessenger.Default.Send(new ShowErrorMessage(ex));
        }
    }

    private void ApplyFilter()
    {
        var filtered = (String.IsNullOrEmpty(SearchText) ? AllImages :
            new ObservableCollection<ImageItem>(AllImages.Where(i => i.DisplayName.Contains(SearchText, StringComparison.OrdinalIgnoreCase))))
            .OrderBy(comparer => comparer.DisplayName);

        FilteredImages.Clear();
        foreach (var it in filtered)
        {
            FilteredImages.Add(it);
        }

        OnPropertyChanged(nameof(FilteredImages));
    }

    private static async Task PreviewAsync(ImageItem item)
    {
        if (item == null)
        {
            return;
        }

        try
        {
            var page = new Views.ImagePreviewPage(item);
            var windows = Application.Current?.Windows;
            var mainPage = (windows != null && windows.Count > 0) ? windows[0].Page : null;
            if (mainPage?.Navigation != null)
            {
                await mainPage.Navigation.PushModalAsync(page).ConfigureAwait(true);
            }
        }
        catch (Exception ex)
        {
            WeakReferenceMessenger.Default.Send(new ShowErrorMessage(ex));
        }
    }

    private void OnPropertyChanged(string name) => PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(name));
}
